// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: entpb/ext.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeeByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByUserIdRequest) Reset() {
	*x = GetEmployeeByUserIdRequest{}
	mi := &file_entpb_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByUserIdRequest) ProtoMessage() {}

func (x *GetEmployeeByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_entpb_ext_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeeByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteEmployeeByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeByUserIdRequest) Reset() {
	*x = DeleteEmployeeByUserIdRequest{}
	mi := &file_entpb_ext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeByUserIdRequest) ProtoMessage() {}

func (x *DeleteEmployeeByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entpb_ext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeByUserIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_entpb_ext_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteEmployeeByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_entpb_ext_proto protoreflect.FileDescriptor

const file_entpb_ext_proto_rawDesc = "" +
	"\n" +
	"\x0fentpb/ext.proto\x12\x05entpb\x1a\x11entpb/entpb.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\x1aGetEmployeeByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1dDeleteEmployeeByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xaf\x01\n" +
	"\n" +
	"ExtService\x12I\n" +
	"\x13GetEmployeeByUserId\x12!.entpb.GetEmployeeByUserIdRequest\x1a\x0f.entpb.Employee\x12V\n" +
	"\x16DeleteEmployeeByUserId\x12$.entpb.DeleteEmployeeByUserIdRequest\x1a\x16.google.protobuf.EmptyB2Z0github.com/longgggwwww/hrm-ms-hr/ent/proto/entpbb\x06proto3"

var (
	file_entpb_ext_proto_rawDescOnce sync.Once
	file_entpb_ext_proto_rawDescData []byte
)

func file_entpb_ext_proto_rawDescGZIP() []byte {
	file_entpb_ext_proto_rawDescOnce.Do(func() {
		file_entpb_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entpb_ext_proto_rawDesc), len(file_entpb_ext_proto_rawDesc)))
	})
	return file_entpb_ext_proto_rawDescData
}

var file_entpb_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entpb_ext_proto_goTypes = []any{
	(*GetEmployeeByUserIdRequest)(nil),    // 0: entpb.GetEmployeeByUserIdRequest
	(*DeleteEmployeeByUserIdRequest)(nil), // 1: entpb.DeleteEmployeeByUserIdRequest
	(*Employee)(nil),                      // 2: entpb.Employee
	(*emptypb.Empty)(nil),                 // 3: google.protobuf.Empty
}
var file_entpb_ext_proto_depIdxs = []int32{
	0, // 0: entpb.ExtService.GetEmployeeByUserId:input_type -> entpb.GetEmployeeByUserIdRequest
	1, // 1: entpb.ExtService.DeleteEmployeeByUserId:input_type -> entpb.DeleteEmployeeByUserIdRequest
	2, // 2: entpb.ExtService.GetEmployeeByUserId:output_type -> entpb.Employee
	3, // 3: entpb.ExtService.DeleteEmployeeByUserId:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entpb_ext_proto_init() }
func file_entpb_ext_proto_init() {
	if File_entpb_ext_proto != nil {
		return
	}
	file_entpb_entpb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_ext_proto_rawDesc), len(file_entpb_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_ext_proto_goTypes,
		DependencyIndexes: file_entpb_ext_proto_depIdxs,
		MessageInfos:      file_entpb_ext_proto_msgTypes,
	}.Build()
	File_entpb_ext_proto = out.File
	file_entpb_ext_proto_goTypes = nil
	file_entpb_ext_proto_depIdxs = nil
}
