services:
  core_app:
    container_name: hrm_core
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5000" # GRPC
      - "8081:8080"
    environment:
      GIN_MODE: ${GIN_MODE:-debug}
      DB_URL: ${DB_URL:-postgres://${DB_USER}:${DB_PASS}@core_postgres:5432/${DB_NAME}?sslmode=disable}
      USER_SERVICE: ${USER_SERVICE:-user_app:8080}
    volumes:
      - .:/app
    depends_on:
      - core_postgres
    networks:
      - shared_network

  core_postgres:
    image: postgres:16-alpine
    container_name: hrm_core_postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASS:-123456}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  data:
    name: hrm_core_data

networks:
  shared_network:
    name: hrm_shared_network
    external: true
