// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwwww/hrm-ms-hr/ent/appointmenthistory"
	"github.com/longgggwwww/hrm-ms-hr/ent/predicate"
)

// AppointmentHistoryDelete is the builder for deleting a AppointmentHistory entity.
type AppointmentHistoryDelete struct {
	config
	hooks    []Hook
	mutation *AppointmentHistoryMutation
}

// Where appends a list predicates to the AppointmentHistoryDelete builder.
func (ahd *AppointmentHistoryDelete) Where(ps ...predicate.AppointmentHistory) *AppointmentHistoryDelete {
	ahd.mutation.Where(ps...)
	return ahd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ahd *AppointmentHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ahd.sqlExec, ahd.mutation, ahd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ahd *AppointmentHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ahd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ahd *AppointmentHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(appointmenthistory.Table, sqlgraph.NewFieldSpec(appointmenthistory.FieldID, field.TypeInt))
	if ps := ahd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ahd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ahd.mutation.done = true
	return affected, err
}

// AppointmentHistoryDeleteOne is the builder for deleting a single AppointmentHistory entity.
type AppointmentHistoryDeleteOne struct {
	ahd *AppointmentHistoryDelete
}

// Where appends a list predicates to the AppointmentHistoryDelete builder.
func (ahdo *AppointmentHistoryDeleteOne) Where(ps ...predicate.AppointmentHistory) *AppointmentHistoryDeleteOne {
	ahdo.ahd.mutation.Where(ps...)
	return ahdo
}

// Exec executes the deletion query.
func (ahdo *AppointmentHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ahdo.ahd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appointmenthistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ahdo *AppointmentHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ahdo.Exec(ctx); err != nil {
		panic(err)
	}
}
