// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwwww/hrm-ms-hr/ent/employee"
	"github.com/longgggwwww/hrm-ms-hr/ent/position"
	"github.com/longgggwwww/hrm-ms-hr/ent/predicate"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUserID sets the "user_id" field.
func (eu *EmployeeUpdate) SetUserID(s string) *EmployeeUpdate {
	eu.mutation.SetUserID(s)
	return eu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableUserID(s *string) *EmployeeUpdate {
	if s != nil {
		eu.SetUserID(*s)
	}
	return eu
}

// ClearUserID clears the value of the "user_id" field.
func (eu *EmployeeUpdate) ClearUserID() *EmployeeUpdate {
	eu.mutation.ClearUserID()
	return eu
}

// SetCode sets the "code" field.
func (eu *EmployeeUpdate) SetCode(s string) *EmployeeUpdate {
	eu.mutation.SetCode(s)
	return eu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableCode(s *string) *EmployeeUpdate {
	if s != nil {
		eu.SetCode(*s)
	}
	return eu
}

// SetStatus sets the "status" field.
func (eu *EmployeeUpdate) SetStatus(e employee.Status) *EmployeeUpdate {
	eu.mutation.SetStatus(e)
	return eu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableStatus(e *employee.Status) *EmployeeUpdate {
	if e != nil {
		eu.SetStatus(*e)
	}
	return eu
}

// SetPositionID sets the "position_id" field.
func (eu *EmployeeUpdate) SetPositionID(i int) *EmployeeUpdate {
	eu.mutation.SetPositionID(i)
	return eu
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillablePositionID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetPositionID(*i)
	}
	return eu
}

// SetJoiningAt sets the "joining_at" field.
func (eu *EmployeeUpdate) SetJoiningAt(t time.Time) *EmployeeUpdate {
	eu.mutation.SetJoiningAt(t)
	return eu
}

// SetNillableJoiningAt sets the "joining_at" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableJoiningAt(t *time.Time) *EmployeeUpdate {
	if t != nil {
		eu.SetJoiningAt(*t)
	}
	return eu
}

// SetOrgID sets the "org_id" field.
func (eu *EmployeeUpdate) SetOrgID(i int) *EmployeeUpdate {
	eu.mutation.ResetOrgID()
	eu.mutation.SetOrgID(i)
	return eu
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableOrgID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetOrgID(*i)
	}
	return eu
}

// AddOrgID adds i to the "org_id" field.
func (eu *EmployeeUpdate) AddOrgID(i int) *EmployeeUpdate {
	eu.mutation.AddOrgID(i)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *EmployeeUpdate) SetUpdatedAt(t time.Time) *EmployeeUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetPosition sets the "position" edge to the Position entity.
func (eu *EmployeeUpdate) SetPosition(p *Position) *EmployeeUpdate {
	return eu.SetPositionID(p.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// ClearPosition clears the "position" edge to the Position entity.
func (eu *EmployeeUpdate) ClearPosition() *EmployeeUpdate {
	eu.mutation.ClearPosition()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EmployeeUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EmployeeUpdate) check() error {
	if v, ok := eu.mutation.Code(); ok {
		if err := employee.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Employee.code": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Status(); ok {
		if err := employee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Employee.status": %w`, err)}
		}
	}
	if eu.mutation.PositionCleared() && len(eu.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.position"`)
	}
	return nil
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UserID(); ok {
		_spec.SetField(employee.FieldUserID, field.TypeString, value)
	}
	if eu.mutation.UserIDCleared() {
		_spec.ClearField(employee.FieldUserID, field.TypeString)
	}
	if value, ok := eu.mutation.Code(); ok {
		_spec.SetField(employee.FieldCode, field.TypeString, value)
	}
	if value, ok := eu.mutation.Status(); ok {
		_spec.SetField(employee.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := eu.mutation.JoiningAt(); ok {
		_spec.SetField(employee.FieldJoiningAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.OrgID(); ok {
		_spec.SetField(employee.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := eu.mutation.AddedOrgID(); ok {
		_spec.AddField(employee.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if eu.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PositionTable,
			Columns: []string{employee.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PositionTable,
			Columns: []string{employee.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetUserID sets the "user_id" field.
func (euo *EmployeeUpdateOne) SetUserID(s string) *EmployeeUpdateOne {
	euo.mutation.SetUserID(s)
	return euo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableUserID(s *string) *EmployeeUpdateOne {
	if s != nil {
		euo.SetUserID(*s)
	}
	return euo
}

// ClearUserID clears the value of the "user_id" field.
func (euo *EmployeeUpdateOne) ClearUserID() *EmployeeUpdateOne {
	euo.mutation.ClearUserID()
	return euo
}

// SetCode sets the "code" field.
func (euo *EmployeeUpdateOne) SetCode(s string) *EmployeeUpdateOne {
	euo.mutation.SetCode(s)
	return euo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableCode(s *string) *EmployeeUpdateOne {
	if s != nil {
		euo.SetCode(*s)
	}
	return euo
}

// SetStatus sets the "status" field.
func (euo *EmployeeUpdateOne) SetStatus(e employee.Status) *EmployeeUpdateOne {
	euo.mutation.SetStatus(e)
	return euo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableStatus(e *employee.Status) *EmployeeUpdateOne {
	if e != nil {
		euo.SetStatus(*e)
	}
	return euo
}

// SetPositionID sets the "position_id" field.
func (euo *EmployeeUpdateOne) SetPositionID(i int) *EmployeeUpdateOne {
	euo.mutation.SetPositionID(i)
	return euo
}

// SetNillablePositionID sets the "position_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillablePositionID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetPositionID(*i)
	}
	return euo
}

// SetJoiningAt sets the "joining_at" field.
func (euo *EmployeeUpdateOne) SetJoiningAt(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetJoiningAt(t)
	return euo
}

// SetNillableJoiningAt sets the "joining_at" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableJoiningAt(t *time.Time) *EmployeeUpdateOne {
	if t != nil {
		euo.SetJoiningAt(*t)
	}
	return euo
}

// SetOrgID sets the "org_id" field.
func (euo *EmployeeUpdateOne) SetOrgID(i int) *EmployeeUpdateOne {
	euo.mutation.ResetOrgID()
	euo.mutation.SetOrgID(i)
	return euo
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableOrgID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetOrgID(*i)
	}
	return euo
}

// AddOrgID adds i to the "org_id" field.
func (euo *EmployeeUpdateOne) AddOrgID(i int) *EmployeeUpdateOne {
	euo.mutation.AddOrgID(i)
	return euo
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *EmployeeUpdateOne) SetUpdatedAt(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetPosition sets the "position" edge to the Position entity.
func (euo *EmployeeUpdateOne) SetPosition(p *Position) *EmployeeUpdateOne {
	return euo.SetPositionID(p.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// ClearPosition clears the "position" edge to the Position entity.
func (euo *EmployeeUpdateOne) ClearPosition() *EmployeeUpdateOne {
	euo.mutation.ClearPosition()
	return euo
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (euo *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Employee entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EmployeeUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EmployeeUpdateOne) check() error {
	if v, ok := euo.mutation.Code(); ok {
		if err := employee.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Employee.code": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Status(); ok {
		if err := employee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Employee.status": %w`, err)}
		}
	}
	if euo.mutation.PositionCleared() && len(euo.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.position"`)
	}
	return nil
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UserID(); ok {
		_spec.SetField(employee.FieldUserID, field.TypeString, value)
	}
	if euo.mutation.UserIDCleared() {
		_spec.ClearField(employee.FieldUserID, field.TypeString)
	}
	if value, ok := euo.mutation.Code(); ok {
		_spec.SetField(employee.FieldCode, field.TypeString, value)
	}
	if value, ok := euo.mutation.Status(); ok {
		_spec.SetField(employee.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := euo.mutation.JoiningAt(); ok {
		_spec.SetField(employee.FieldJoiningAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.OrgID(); ok {
		_spec.SetField(employee.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := euo.mutation.AddedOrgID(); ok {
		_spec.AddField(employee.FieldOrgID, field.TypeInt, value)
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if euo.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PositionTable,
			Columns: []string{employee.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.PositionTable,
			Columns: []string{employee.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
