// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwwww/hrm-ms-hr/ent/leaveapproval"
	"github.com/longgggwwww/hrm-ms-hr/ent/predicate"
)

// LeaveApprovalDelete is the builder for deleting a LeaveApproval entity.
type LeaveApprovalDelete struct {
	config
	hooks    []Hook
	mutation *LeaveApprovalMutation
}

// Where appends a list predicates to the LeaveApprovalDelete builder.
func (lad *LeaveApprovalDelete) Where(ps ...predicate.LeaveApproval) *LeaveApprovalDelete {
	lad.mutation.Where(ps...)
	return lad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lad *LeaveApprovalDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lad.sqlExec, lad.mutation, lad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lad *LeaveApprovalDelete) ExecX(ctx context.Context) int {
	n, err := lad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lad *LeaveApprovalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(leaveapproval.Table, sqlgraph.NewFieldSpec(leaveapproval.FieldID, field.TypeInt))
	if ps := lad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lad.mutation.done = true
	return affected, err
}

// LeaveApprovalDeleteOne is the builder for deleting a single LeaveApproval entity.
type LeaveApprovalDeleteOne struct {
	lad *LeaveApprovalDelete
}

// Where appends a list predicates to the LeaveApprovalDelete builder.
func (lado *LeaveApprovalDeleteOne) Where(ps ...predicate.LeaveApproval) *LeaveApprovalDeleteOne {
	lado.lad.mutation.Where(ps...)
	return lado
}

// Exec executes the deletion query.
func (lado *LeaveApprovalDeleteOne) Exec(ctx context.Context) error {
	n, err := lado.lad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{leaveapproval.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lado *LeaveApprovalDeleteOne) ExecX(ctx context.Context) {
	if err := lado.Exec(ctx); err != nil {
		panic(err)
	}
}
