// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwwww/hrm-ms-hr/ent/employee"
	"github.com/longgggwwww/hrm-ms-hr/ent/label"
	"github.com/longgggwwww/hrm-ms-hr/ent/project"
	"github.com/longgggwwww/hrm-ms-hr/ent/task"
	"github.com/longgggwwww/hrm-ms-hr/ent/taskreport"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (tc *TaskCreate) SetName(s string) *TaskCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetCode sets the "code" field.
func (tc *TaskCreate) SetCode(s string) *TaskCreate {
	tc.mutation.SetCode(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TaskCreate) SetDescription(s string) *TaskCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tc *TaskCreate) SetNillableDescription(s *string) *TaskCreate {
	if s != nil {
		tc.SetDescription(*s)
	}
	return tc
}

// SetProcess sets the "process" field.
func (tc *TaskCreate) SetProcess(i int) *TaskCreate {
	tc.mutation.SetProcess(i)
	return tc
}

// SetNillableProcess sets the "process" field if the given value is not nil.
func (tc *TaskCreate) SetNillableProcess(i *int) *TaskCreate {
	if i != nil {
		tc.SetProcess(*i)
	}
	return tc
}

// SetStatus sets the "status" field.
func (tc *TaskCreate) SetStatus(t task.Status) *TaskCreate {
	tc.mutation.SetStatus(t)
	return tc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tc *TaskCreate) SetNillableStatus(t *task.Status) *TaskCreate {
	if t != nil {
		tc.SetStatus(*t)
	}
	return tc
}

// SetStartAt sets the "start_at" field.
func (tc *TaskCreate) SetStartAt(t time.Time) *TaskCreate {
	tc.mutation.SetStartAt(t)
	return tc
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableStartAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetStartAt(*t)
	}
	return tc
}

// SetDueDate sets the "due_date" field.
func (tc *TaskCreate) SetDueDate(t time.Time) *TaskCreate {
	tc.mutation.SetDueDate(t)
	return tc
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (tc *TaskCreate) SetNillableDueDate(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetDueDate(*t)
	}
	return tc
}

// SetProjectID sets the "project_id" field.
func (tc *TaskCreate) SetProjectID(i int) *TaskCreate {
	tc.mutation.SetProjectID(i)
	return tc
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tc *TaskCreate) SetNillableProjectID(i *int) *TaskCreate {
	if i != nil {
		tc.SetProjectID(*i)
	}
	return tc
}

// SetCreatorID sets the "creator_id" field.
func (tc *TaskCreate) SetCreatorID(i int) *TaskCreate {
	tc.mutation.SetCreatorID(i)
	return tc
}

// SetUpdaterID sets the "updater_id" field.
func (tc *TaskCreate) SetUpdaterID(i int) *TaskCreate {
	tc.mutation.SetUpdaterID(i)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TaskCreate) SetCreatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableCreatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TaskCreate) SetUpdatedAt(t time.Time) *TaskCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TaskCreate) SetNillableUpdatedAt(t *time.Time) *TaskCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetType sets the "type" field.
func (tc *TaskCreate) SetType(t task.Type) *TaskCreate {
	tc.mutation.SetType(t)
	return tc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tc *TaskCreate) SetNillableType(t *task.Type) *TaskCreate {
	if t != nil {
		tc.SetType(*t)
	}
	return tc
}

// SetProject sets the "project" edge to the Project entity.
func (tc *TaskCreate) SetProject(p *Project) *TaskCreate {
	return tc.SetProjectID(p.ID)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (tc *TaskCreate) AddLabelIDs(ids ...int) *TaskCreate {
	tc.mutation.AddLabelIDs(ids...)
	return tc
}

// AddLabels adds the "labels" edges to the Label entity.
func (tc *TaskCreate) AddLabels(l ...*Label) *TaskCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tc.AddLabelIDs(ids...)
}

// AddAssigneeIDs adds the "assignees" edge to the Employee entity by IDs.
func (tc *TaskCreate) AddAssigneeIDs(ids ...int) *TaskCreate {
	tc.mutation.AddAssigneeIDs(ids...)
	return tc
}

// AddAssignees adds the "assignees" edges to the Employee entity.
func (tc *TaskCreate) AddAssignees(e ...*Employee) *TaskCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tc.AddAssigneeIDs(ids...)
}

// AddReportIDs adds the "reports" edge to the TaskReport entity by IDs.
func (tc *TaskCreate) AddReportIDs(ids ...int) *TaskCreate {
	tc.mutation.AddReportIDs(ids...)
	return tc
}

// AddReports adds the "reports" edges to the TaskReport entity.
func (tc *TaskCreate) AddReports(t ...*TaskReport) *TaskCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tc.AddReportIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tc *TaskCreate) Mutation() *TaskMutation {
	return tc.mutation
}

// Save creates the Task in the database.
func (tc *TaskCreate) Save(ctx context.Context) (*Task, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TaskCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TaskCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TaskCreate) defaults() {
	if _, ok := tc.mutation.Process(); !ok {
		v := task.DefaultProcess
		tc.mutation.SetProcess(v)
	}
	if _, ok := tc.mutation.Status(); !ok {
		v := task.DefaultStatus
		tc.mutation.SetStatus(v)
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tc.mutation.GetType(); !ok {
		v := task.DefaultType
		tc.mutation.SetType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TaskCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Task.name"`)}
	}
	if _, ok := tc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Task.code"`)}
	}
	if _, ok := tc.mutation.Process(); !ok {
		return &ValidationError{Name: "process", err: errors.New(`ent: missing required field "Task.process"`)}
	}
	if _, ok := tc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if v, ok := tc.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if _, ok := tc.mutation.CreatorID(); !ok {
		return &ValidationError{Name: "creator_id", err: errors.New(`ent: missing required field "Task.creator_id"`)}
	}
	if _, ok := tc.mutation.UpdaterID(); !ok {
		return &ValidationError{Name: "updater_id", err: errors.New(`ent: missing required field "Task.updater_id"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	if _, ok := tc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Task.type"`)}
	}
	if v, ok := tc.mutation.GetType(); ok {
		if err := task.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Task.type": %w`, err)}
		}
	}
	return nil
}

func (tc *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	_spec.OnConflict = tc.conflict
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(task.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Code(); ok {
		_spec.SetField(task.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.Process(); ok {
		_spec.SetField(task.FieldProcess, field.TypeInt, value)
		_node.Process = value
	}
	if value, ok := tc.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := tc.mutation.StartAt(); ok {
		_spec.SetField(task.FieldStartAt, field.TypeTime, value)
		_node.StartAt = value
	}
	if value, ok := tc.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := tc.mutation.CreatorID(); ok {
		_spec.SetField(task.FieldCreatorID, field.TypeInt, value)
		_node.CreatorID = value
	}
	if value, ok := tc.mutation.UpdaterID(); ok {
		_spec.SetField(task.FieldUpdaterID, field.TypeInt, value)
		_node.UpdaterID = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := tc.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := tc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.LabelsTable,
			Columns: task.LabelsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.AssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   task.AssigneesTable,
			Columns: task.AssigneesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.ReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ReportsTable,
			Columns: []string{task.ReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskreport.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Task.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tc *TaskCreate) OnConflict(opts ...sql.ConflictOption) *TaskUpsertOne {
	tc.conflict = opts
	return &TaskUpsertOne{
		create: tc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tc *TaskCreate) OnConflictColumns(columns ...string) *TaskUpsertOne {
	tc.conflict = append(tc.conflict, sql.ConflictColumns(columns...))
	return &TaskUpsertOne{
		create: tc,
	}
}

type (
	// TaskUpsertOne is the builder for "upsert"-ing
	//  one Task node.
	TaskUpsertOne struct {
		create *TaskCreate
	}

	// TaskUpsert is the "OnConflict" setter.
	TaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TaskUpsert) SetName(v string) *TaskUpsert {
	u.Set(task.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TaskUpsert) UpdateName() *TaskUpsert {
	u.SetExcluded(task.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *TaskUpsert) SetCode(v string) *TaskUpsert {
	u.Set(task.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskUpsert) UpdateCode() *TaskUpsert {
	u.SetExcluded(task.FieldCode)
	return u
}

// SetDescription sets the "description" field.
func (u *TaskUpsert) SetDescription(v string) *TaskUpsert {
	u.Set(task.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskUpsert) UpdateDescription() *TaskUpsert {
	u.SetExcluded(task.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TaskUpsert) ClearDescription() *TaskUpsert {
	u.SetNull(task.FieldDescription)
	return u
}

// SetProcess sets the "process" field.
func (u *TaskUpsert) SetProcess(v int) *TaskUpsert {
	u.Set(task.FieldProcess, v)
	return u
}

// UpdateProcess sets the "process" field to the value that was provided on create.
func (u *TaskUpsert) UpdateProcess() *TaskUpsert {
	u.SetExcluded(task.FieldProcess)
	return u
}

// AddProcess adds v to the "process" field.
func (u *TaskUpsert) AddProcess(v int) *TaskUpsert {
	u.Add(task.FieldProcess, v)
	return u
}

// SetStatus sets the "status" field.
func (u *TaskUpsert) SetStatus(v task.Status) *TaskUpsert {
	u.Set(task.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskUpsert) UpdateStatus() *TaskUpsert {
	u.SetExcluded(task.FieldStatus)
	return u
}

// SetStartAt sets the "start_at" field.
func (u *TaskUpsert) SetStartAt(v time.Time) *TaskUpsert {
	u.Set(task.FieldStartAt, v)
	return u
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *TaskUpsert) UpdateStartAt() *TaskUpsert {
	u.SetExcluded(task.FieldStartAt)
	return u
}

// ClearStartAt clears the value of the "start_at" field.
func (u *TaskUpsert) ClearStartAt() *TaskUpsert {
	u.SetNull(task.FieldStartAt)
	return u
}

// SetDueDate sets the "due_date" field.
func (u *TaskUpsert) SetDueDate(v time.Time) *TaskUpsert {
	u.Set(task.FieldDueDate, v)
	return u
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *TaskUpsert) UpdateDueDate() *TaskUpsert {
	u.SetExcluded(task.FieldDueDate)
	return u
}

// ClearDueDate clears the value of the "due_date" field.
func (u *TaskUpsert) ClearDueDate() *TaskUpsert {
	u.SetNull(task.FieldDueDate)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *TaskUpsert) SetProjectID(v int) *TaskUpsert {
	u.Set(task.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateProjectID() *TaskUpsert {
	u.SetExcluded(task.FieldProjectID)
	return u
}

// ClearProjectID clears the value of the "project_id" field.
func (u *TaskUpsert) ClearProjectID() *TaskUpsert {
	u.SetNull(task.FieldProjectID)
	return u
}

// SetCreatorID sets the "creator_id" field.
func (u *TaskUpsert) SetCreatorID(v int) *TaskUpsert {
	u.Set(task.FieldCreatorID, v)
	return u
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateCreatorID() *TaskUpsert {
	u.SetExcluded(task.FieldCreatorID)
	return u
}

// AddCreatorID adds v to the "creator_id" field.
func (u *TaskUpsert) AddCreatorID(v int) *TaskUpsert {
	u.Add(task.FieldCreatorID, v)
	return u
}

// SetUpdaterID sets the "updater_id" field.
func (u *TaskUpsert) SetUpdaterID(v int) *TaskUpsert {
	u.Set(task.FieldUpdaterID, v)
	return u
}

// UpdateUpdaterID sets the "updater_id" field to the value that was provided on create.
func (u *TaskUpsert) UpdateUpdaterID() *TaskUpsert {
	u.SetExcluded(task.FieldUpdaterID)
	return u
}

// AddUpdaterID adds v to the "updater_id" field.
func (u *TaskUpsert) AddUpdaterID(v int) *TaskUpsert {
	u.Add(task.FieldUpdaterID, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskUpsert) SetUpdatedAt(v time.Time) *TaskUpsert {
	u.Set(task.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskUpsert) UpdateUpdatedAt() *TaskUpsert {
	u.SetExcluded(task.FieldUpdatedAt)
	return u
}

// SetType sets the "type" field.
func (u *TaskUpsert) SetType(v task.Type) *TaskUpsert {
	u.Set(task.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TaskUpsert) UpdateType() *TaskUpsert {
	u.SetExcluded(task.FieldType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TaskUpsertOne) UpdateNewValues() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(task.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskUpsertOne) Ignore() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskUpsertOne) DoNothing() *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskCreate.OnConflict
// documentation for more info.
func (u *TaskUpsertOne) Update(set func(*TaskUpsert)) *TaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TaskUpsertOne) SetName(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateName() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *TaskUpsertOne) SetCode(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateCode() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCode()
	})
}

// SetDescription sets the "description" field.
func (u *TaskUpsertOne) SetDescription(v string) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateDescription() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TaskUpsertOne) ClearDescription() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearDescription()
	})
}

// SetProcess sets the "process" field.
func (u *TaskUpsertOne) SetProcess(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetProcess(v)
	})
}

// AddProcess adds v to the "process" field.
func (u *TaskUpsertOne) AddProcess(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.AddProcess(v)
	})
}

// UpdateProcess sets the "process" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateProcess() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateProcess()
	})
}

// SetStatus sets the "status" field.
func (u *TaskUpsertOne) SetStatus(v task.Status) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateStatus() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateStatus()
	})
}

// SetStartAt sets the "start_at" field.
func (u *TaskUpsertOne) SetStartAt(v time.Time) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateStartAt() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateStartAt()
	})
}

// ClearStartAt clears the value of the "start_at" field.
func (u *TaskUpsertOne) ClearStartAt() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearStartAt()
	})
}

// SetDueDate sets the "due_date" field.
func (u *TaskUpsertOne) SetDueDate(v time.Time) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateDueDate() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateDueDate()
	})
}

// ClearDueDate clears the value of the "due_date" field.
func (u *TaskUpsertOne) ClearDueDate() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearDueDate()
	})
}

// SetProjectID sets the "project_id" field.
func (u *TaskUpsertOne) SetProjectID(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateProjectID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *TaskUpsertOne) ClearProjectID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.ClearProjectID()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *TaskUpsertOne) SetCreatorID(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetCreatorID(v)
	})
}

// AddCreatorID adds v to the "creator_id" field.
func (u *TaskUpsertOne) AddCreatorID(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.AddCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateCreatorID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCreatorID()
	})
}

// SetUpdaterID sets the "updater_id" field.
func (u *TaskUpsertOne) SetUpdaterID(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdaterID(v)
	})
}

// AddUpdaterID adds v to the "updater_id" field.
func (u *TaskUpsertOne) AddUpdaterID(v int) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.AddUpdaterID(v)
	})
}

// UpdateUpdaterID sets the "updater_id" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateUpdaterID() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdaterID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskUpsertOne) SetUpdatedAt(v time.Time) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateUpdatedAt() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetType sets the "type" field.
func (u *TaskUpsertOne) SetType(v task.Type) *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TaskUpsertOne) UpdateType() *TaskUpsertOne {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *TaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
	conflict []sql.ConflictOption
}

// Save creates the Task entities in the database.
func (tcb *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Task, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Task.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tcb *TaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskUpsertBulk {
	tcb.conflict = opts
	return &TaskUpsertBulk{
		create: tcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcb *TaskCreateBulk) OnConflictColumns(columns ...string) *TaskUpsertBulk {
	tcb.conflict = append(tcb.conflict, sql.ConflictColumns(columns...))
	return &TaskUpsertBulk{
		create: tcb,
	}
}

// TaskUpsertBulk is the builder for "upsert"-ing
// a bulk of Task nodes.
type TaskUpsertBulk struct {
	create *TaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TaskUpsertBulk) UpdateNewValues() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(task.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Task.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskUpsertBulk) Ignore() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskUpsertBulk) DoNothing() *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskCreateBulk.OnConflict
// documentation for more info.
func (u *TaskUpsertBulk) Update(set func(*TaskUpsert)) *TaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TaskUpsertBulk) SetName(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateName() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *TaskUpsertBulk) SetCode(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateCode() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCode()
	})
}

// SetDescription sets the "description" field.
func (u *TaskUpsertBulk) SetDescription(v string) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateDescription() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TaskUpsertBulk) ClearDescription() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearDescription()
	})
}

// SetProcess sets the "process" field.
func (u *TaskUpsertBulk) SetProcess(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetProcess(v)
	})
}

// AddProcess adds v to the "process" field.
func (u *TaskUpsertBulk) AddProcess(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.AddProcess(v)
	})
}

// UpdateProcess sets the "process" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateProcess() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateProcess()
	})
}

// SetStatus sets the "status" field.
func (u *TaskUpsertBulk) SetStatus(v task.Status) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateStatus() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateStatus()
	})
}

// SetStartAt sets the "start_at" field.
func (u *TaskUpsertBulk) SetStartAt(v time.Time) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetStartAt(v)
	})
}

// UpdateStartAt sets the "start_at" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateStartAt() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateStartAt()
	})
}

// ClearStartAt clears the value of the "start_at" field.
func (u *TaskUpsertBulk) ClearStartAt() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearStartAt()
	})
}

// SetDueDate sets the "due_date" field.
func (u *TaskUpsertBulk) SetDueDate(v time.Time) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateDueDate() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateDueDate()
	})
}

// ClearDueDate clears the value of the "due_date" field.
func (u *TaskUpsertBulk) ClearDueDate() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearDueDate()
	})
}

// SetProjectID sets the "project_id" field.
func (u *TaskUpsertBulk) SetProjectID(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateProjectID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateProjectID()
	})
}

// ClearProjectID clears the value of the "project_id" field.
func (u *TaskUpsertBulk) ClearProjectID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.ClearProjectID()
	})
}

// SetCreatorID sets the "creator_id" field.
func (u *TaskUpsertBulk) SetCreatorID(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetCreatorID(v)
	})
}

// AddCreatorID adds v to the "creator_id" field.
func (u *TaskUpsertBulk) AddCreatorID(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.AddCreatorID(v)
	})
}

// UpdateCreatorID sets the "creator_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateCreatorID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateCreatorID()
	})
}

// SetUpdaterID sets the "updater_id" field.
func (u *TaskUpsertBulk) SetUpdaterID(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdaterID(v)
	})
}

// AddUpdaterID adds v to the "updater_id" field.
func (u *TaskUpsertBulk) AddUpdaterID(v int) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.AddUpdaterID(v)
	})
}

// UpdateUpdaterID sets the "updater_id" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateUpdaterID() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdaterID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskUpsertBulk) SetUpdatedAt(v time.Time) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateUpdatedAt() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetType sets the "type" field.
func (u *TaskUpsertBulk) SetType(v task.Type) *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *TaskUpsertBulk) UpdateType() *TaskUpsertBulk {
	return u.Update(func(s *TaskUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *TaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
