// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/longgggwwww/hrm-ms-hr/ent/predicate"
	"github.com/longgggwwww/hrm-ms-hr/ent/zaloemployee"
)

// ZaloEmployeeDelete is the builder for deleting a ZaloEmployee entity.
type ZaloEmployeeDelete struct {
	config
	hooks    []Hook
	mutation *ZaloEmployeeMutation
}

// Where appends a list predicates to the ZaloEmployeeDelete builder.
func (zed *ZaloEmployeeDelete) Where(ps ...predicate.ZaloEmployee) *ZaloEmployeeDelete {
	zed.mutation.Where(ps...)
	return zed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (zed *ZaloEmployeeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, zed.sqlExec, zed.mutation, zed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (zed *ZaloEmployeeDelete) ExecX(ctx context.Context) int {
	n, err := zed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (zed *ZaloEmployeeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(zaloemployee.Table, sqlgraph.NewFieldSpec(zaloemployee.FieldID, field.TypeInt))
	if ps := zed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, zed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	zed.mutation.done = true
	return affected, err
}

// ZaloEmployeeDeleteOne is the builder for deleting a single ZaloEmployee entity.
type ZaloEmployeeDeleteOne struct {
	zed *ZaloEmployeeDelete
}

// Where appends a list predicates to the ZaloEmployeeDelete builder.
func (zedo *ZaloEmployeeDeleteOne) Where(ps ...predicate.ZaloEmployee) *ZaloEmployeeDeleteOne {
	zedo.zed.mutation.Where(ps...)
	return zedo
}

// Exec executes the deletion query.
func (zedo *ZaloEmployeeDeleteOne) Exec(ctx context.Context) error {
	n, err := zedo.zed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{zaloemployee.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (zedo *ZaloEmployeeDeleteOne) ExecX(ctx context.Context) {
	if err := zedo.Exec(ctx); err != nil {
		panic(err)
	}
}
