// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppointmentHistory is the predicate function for appointmenthistory builders.
type AppointmentHistory func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// LeaveApproval is the predicate function for leaveapproval builders.
type LeaveApproval func(*sql.Selector)

// LeaveRequest is the predicate function for leaverequest builders.
type LeaveRequest func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskReport is the predicate function for taskreport builders.
type TaskReport func(*sql.Selector)

// ZaloDepartment is the predicate function for zalodepartment builders.
type ZaloDepartment func(*sql.Selector)

// ZaloEmployee is the predicate function for zaloemployee builders.
type ZaloEmployee func(*sql.Selector)
