// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Branch is the predicate function for branch builders.
type Branch func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// LeaveApproval is the predicate function for leaveapproval builders.
type LeaveApproval func(*sql.Selector)

// LeaveRequest is the predicate function for leaverequest builders.
type LeaveRequest func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
